export const SALE_CONFIG_PRESALE = "PRESALE";
export const SALE_CONFIG_FIXED_PRICE = "FIXED_PRICE";
export const SALE_CONFIG_REDEEM_STRATEGY = "REDEEM_STRATEGY";
export const SALE_CONFIG_ERC_20_MINTER = "ERC_20_MINTER";
export const SALE_CONFIG_ZORA_TIMED = "ZORA_TIMED";
