// This file is automatically generated by code; do not manually update
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

import {IVersionedContract} from "@zoralabs/shared-contracts/interfaces/IVersionedContract.sol";

contract ContractVersionBase is IVersionedContract {
    /// @notice The contract version
    function contractVersion() external pure override returns (string memory) {
        return "0.0.0";
    }
}
