@startuml

title Creating a signature for a new erc1155 contract + token

actor Creator
entity CreatePage
boundary SignatureAPI
entity SignatureDB


Group Signature not created for token in contract yet
  
  activate CreatePage
  Creator -> CreatePage: setup NEW contract name + image
  CreatePage -> SignatureAPI: validate that contract \nwith same params for\ncreator doesnt exist
  SignatureAPI -> SignatureDB: check if hash for contract\nis already stored
  SignatureAPI --> CreatePage: validation results

end

Group Signature has been created for token in contract

  Creator -> CreatePage: load page by\ncontract hash
  CreatePage -> SignatureAPI: load contract creation params
  SignatureAPI -> SignatureDB: fetch contract creation params\nby hash
  SignatureAPI --> CreatePage: contract creation params

end

Creator -> CreatePage: setup new token params
CreatePage -> SignatureAPI: validate signature doesnt exist\nfor identitical creator + contract + token
SignatureAPI -> SignatureDB: check if hash for signature\nis already stored
SignatureAPI --> CreatePage: validation results
Creator -> CreatePage: submit
CreatePage -> Creator: request signature of\n data hash
deactivate CreatePage
Creator -> SignatureAPI: Submit signature + contract + token params
SignatureAPI -> SignatureDB: store signature + \ncontract creation + \ntoken creation params

@enduml