@startuml

title Creating a signature for a new erc1155 contract + token

actor Creator
entity CreatePage
boundary SignatureAPI
boundary PremintContract
entity SignatureDB


Group Signature not created for contract yet
  
  activate CreatePage
  Creator -> CreatePage: setup NEW contract name + image
  CreatePage -> SignatureAPI: validate that contract \nwith same params for\ncreator doesnt exist
  SignatureAPI -> SignatureDB: check if signature with hash \nfor contract is already stored
  SignatureAPI --> CreatePage: validation results

end

Group Signature has been created for contract

  Creator -> CreatePage: load page by determinstic collection address 
  CreatePage -> SignatureAPI: load collection creation params
  SignatureAPI -> SignatureDB: fetch collection creation params\nby hash
  SignatureAPI --> CreatePage: contract creation params

end

Creator -> CreatePage: setup new token
CreatePage -> PremintContract: get determnistic collection address
PremintContract --> CreatePage: determinstic collection address
CreatePage -> SignatureAPI: get new uid for collection address
SignatureAPI -> SignatureDB: get next token uid\nscoped to collection address
SignatureDB --> SignatureAPI: next token uid
SignatureAPI --> CreatePage: next token uid
Creator -> CreatePage: Submit new token creation params
CreatePage -> Creator: request signature of\n contract + token creation params + token uid 
deactivate CreatePage
Creator -> SignatureAPI: Submit signature + contract + token params + token uid
SignatureAPI -> PremintContract: validate signature
PremintContract --> SignatureAPI: validation results (true/false & recovered signer)

Group Signature is valid

  SignatureAPI -> SignatureDB: store signature + \ncontract creation + \ntoken creation params + \ncollection address + \ntoken uid

end

@enduml