@startuml
actor Collector
entity PremintCollectPage 
boundary SignatureAPI
entity SignatureDB
entity PreminterContract
entity 1155FactoryContract
entity 1155Contract

Collector -> PremintCollectPage: Open, param is \ndeterministic collection address\n+ token uid
Activate PremintCollectPage
PremintCollectPage -> SignatureAPI: Fetch by collection address\n+ token uid
SignatureAPI -> SignatureDB: Fetch most recent signature\nby contract hash token uid
SignatureDB --> SignatureAPI: contract + token creation params\n+ signature
SignatureAPI --> PremintCollectPage: contract + token creation params\n+ signature
PremintCollectPage -> PreminterContract: Check if signature has been used (by contract hash + token uid)
PreminterContract --> PremintCollectPage: Signature has been used or not

Group signature has been used

    PremintCollectPage -> Collector: Redirect to \nstandard collect page

end

Collector -> PremintCollectPage: mint
PremintCollectPage -> Collector: Submit transaction
deactivate PremintCollectPage
Collector -> PreminterContract: Submit premint transaction containing \nsignature, contract creation & token creation params
activate PreminterContract
PreminterContract -> PreminterContract: record signature used;\nrevert if already used

Group contract doesnt exist
  
    PreminterContract -> 1155FactoryContract: create contract
    1155FactoryContract -> 1155Contract: create
    activate 1155Contract

end

PreminterContract -> 1155Contract: create new token\nwith signature
PreminterContract -> 1155Contract: mint tokens to collector

deactivate PreminterContract
1155Contract --> Collector: Minted tokens
deactivate 1155Contract

@enduml