@startuml

title Creating a signature for a Premint Erc1155 contract + New token

actor Creator
entity Wallet
entity CreateUI
boundary PremintAPI
boundary PremintContract

Group New premint token on new contract
  
  Creator -> CreateUI: setup NEW contract name + image
  activate CreateUI
  CreateUI -> PremintContract: get determnistic collection address\nfor contract creation params
  activate PremintContract
  PremintContract --> CreateUI: determinstic collection address
  deactivate CreateUI
  deactivate PremintContract

end

Group New premint token on existing premint contract

  Creator -> CreateUI: load page to create new token for\npremint at determinstic\ncollection address 
  activate CreateUI
  CreateUI -> PremintAPI: load collection creation params\nby determinstic address
  activate PremintAPI

  Group Premint exists
    PremintAPI --> CreateUI: collection creation params\n(from premint)
    deactivate CreateUI
    deactivate PremintAPI
  end

end

CreateUI -> PremintAPI: get next uid for\ncollection address
activate CreateUI
activate PremintAPI
PremintAPI --> CreateUI: next uid for collection

Creator -> CreateUI: configure new token parameters
Creator -> CreateUI: Submit
CreateUI -> Creator: request Premint EIP-712 signature containing:\n token creation params, token uid, version
Creator -> Wallet: sign message
Wallet -> CreateUI: Signed message by creator of\ntoken creation params, token uid, version
CreateUI -> PremintAPI: validate and store signature
PremintAPI -> PremintContract: validate signature
PremintContract --> PremintAPI: validation results (true/false & recovered signer)

Group Signature is valid
  PremintAPI -> PremintAPI: store premint and signature

end

PremintAPI -> CreateUI: validation & storage status
deactivate CreateUI

@enduml