@startuml

title Collecting with a premint signature

start

:Load signature by\ncontract hash & uid;
if (sig with contract hash + uid\nalready executed) then (yes)
  :Redirect to\nstandard mint page;
  :Mint on erc1155 contract;
  stop
else (no)
  if (contract already created) then (yes)
    :Show contract address;
  endif
  :Submit premint containing:\ncontract & token params, uid, signature\nquantity, comment;
endif
stop

@enduml
