// This file is auto-generated by @hey-api/openapi-ts

import type {
  Options as ClientOptions,
  TDataShape,
} from "@hey-api/client-fetch";

export type RequestOptionsType<TData extends TDataShape> = ClientOptions<TData>;
