name: Vercel CLI Docs Preview Deployment
on:
  pull_request:
    paths:
      - "cli-docs/**"
      - "packages/cli/SKILL.md"

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_CLI_DOCS_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install node deps
        uses: ./.github/actions/setup_deps

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: RM Vercel Cache
        run: rm -rf .vercel

      - name: Copy SKILL.md
        run: cp packages/cli/SKILL.md cli-docs/docs/public/skill.md

      - name: Pull Vercel Environment Information
        working-directory: ./cli-docs
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: ./cli-docs
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VITE_SITE_ROOT_URL: ${{ vars.CLI_DOCS_SITE_ROOT_URL }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
        working-directory: ./cli-docs

      - name: Comment on PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `CLI Docs Preview: ${{ steps.deploy.outputs.url }}`
            })
